resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/dharshan473/concourse
    branch: master

jobs:
- name: run-helloworld
  plan:
  - get: my-git-repo
    trigger: true
  - task: execute-helloworld
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
          tag: 'latest'
      inputs:
      - name: my-git-repo
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          cd my-git-repo
          chmod +x helloworld.sh
          ./helloworld.sh
